baseURL: "https://kirillaristov.com/"

frontmatter:
  date:
    - ":filename"
    - "publishDate"
    - "date"
    - "lastmod"
    - ":default"
  lastmod:
    - "lastmod"
    - ":filename"
    - ":fileModTime"
    - ":git"
    - "date"
    - "publishDate"
    - ":default"
  publishDate:
    - "publishDate"
    - "date"
  expiryDate:
    - "expiryDate"

disableKinds:
  - "404"

taxonomies:
  category: "categories"
  tag: "tags"

permalinks:
  blog: /blog/:filename/
#  blog: /blog/:year:month:day:15:04/
  media: /media/:filename/

disableHugoGeneratorInject: true
disableLiveReload: true
disableFastRender: true
disablePathToLower: true
enableGitInfo: true
# removePathAccents: false (remove accent or special symbols from tags and categories)
enableRobotsTXT: true

paginate: 10
paginatePath: "page"
rssLimit: 15

languageCode: ru
defaultContentLanguage: ru
defaultContentLanguageInSubdir: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

taxonomies:
  category: categories
  tag: tags
  
outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

outputFormats:
  RSS:
    mediatype: "application/rss+xml"
    baseName: "rss"

languages:
  en:
    weight: 2

    title: "Along Bluetrails of Endless Rivers"
    description: "Lifelong routes. Tough equipment development and testing"
    keywords: "Kirill Aristov, Kirill from Fryazino, wild Russia, combining trips, kayak, adventure, journey, voyage, Siberia"
    author: "Kirill Aristov, Russia, https://kirillaristov.com"
    generator: "Effort, Hope and Love. Hugo, Github and Netlify"

    ABOUT_TITLE: "Who I am"
    ABOUT: "I develop long-distance routes In The Wild. The voyage is a tool to discover many sides of our World, to feel the Bliss once more and to understand much more human lives. I spread my ideas, because long hard Voyages are possibility to open rare human personalities, I believe best personalities."
    ABOUT_MORE: "More about me"

    FOOTER:
      TITLE: "Kirill Aristov, Russia"
      LANG_TO: "Switch to Russian"
      LANG_FROM: "You are currently viewing English version"
      SLOGAN: "I am for Peace, for Freedom; Happy Smiles, Dreams coming true and Clear Blue Sky"
      LICENSE: "Content is available under the Creative Commons Attribution-ShareAlike License"

    SUBSCRIBE:
      TITLE: "Subscribe to History"
      EMAIL: "Email"
      SUBMIT: "Subscribe"

    CONTACTS:
      TITLE: "Contacts"
      ADDRESS: "Russia, 141190, Moscow&nbsp;region,<br>Science City Fryazino, Vokzalnaya&nbsp;street, 19,&nbsp;82"
      CEO: "Kirill Aristov"

    dateLastEdited: "January 2, 2006 at 15:04"
    datePosted: "January 2, 2006. 15:04"

    CONTENTS: "Contents"
    READ_MORE: "Read More…"
    FEED: "Feed"
    NEWER: "Newer"
    OLDER: "Older"
    PREVIOUS: "Previous"
    NEXT: "Next page"
    ON_FIRST: "On first page"
    ON_LAST: "On last page"
    DATE: "Date"
    LOCATION: "Location"
    COORDINATES: "Coordinates"
    TAGS: "Tags"

    HOME_PAGE: "Home Page"
    LANG_TO: "Изменить язык на русский"
    LANG_FROM: "&nbsp;In&nbsp;English"

    LAST_EDITED: "This page was last edited on"
    PUBLISHED: "This page was created on"
    EDIT_THIS_PAGE: "Edit this page"
    EDIT_THIS_PAGE_TITLE: "You can edit this page. About how to make changes — on the «How to Contribute» page"

    PAGE: "Page"
    SCROLL_UP: "Scroll Up"

  ru:
    weight: 1

    title: "Голубыми тропинками бесконечных рек"
    description: "Маршруты длиною в жизнь. Разработка и тестирование надёжной экипировки"
    keywords: "Кирилл Аристов, Кирилл из Фрязино, дикая природа России, комбинированные путешествия, каяк, приключение, странствие, Сибирь"
    author: "Кирилл Аристов, Россия, https://kirillaristov.com"
    generator: "Стремление, Надежда и Любовь. Hugo, Github and Netlify"

    ABOUT_TITLE: "Кто Я"
    ABOUT: "Я разрабатываю дальние маршруты в условиях дикой природы. Странствие — это инструмент, открывающий грани нашего мира; это путь к пониманию человеческих жизней; способ почувствовать Счастье ещё один раз. Я распространяю мои идеи, потому что долгие трудные Странствия — это возможности для становления необычных людей, я верю — хороших и нужных людей."
    ABOUT_MORE: "Подробнее обо мне"

    FOOTER:
      TITLE: "Кирилл Аристов, Россия"
      LANG_TO: "Переключить на английский"
      LANG_FROM: "Вы просматриваете русскоязычную версию"
      SLOGAN: "Я за Мир, за Свободу; Счастливые улыбки, Сбывающиеся Мечты и Ясное Голубое Небо"
      LICENSE: "Содержание доступно по лицензии Creative Commons «С указанием авторства — С сохранением условий»"

    SUBSCRIBE:
      TITLE: "Подпишитесь на историю"
      EMAIL: "Email"
      SUBMIT: "Подписаться"

    CONTACTS:
      TITLE: "Контакты"
      ADDRESS: "Россия, 141190, Московская&nbsp;область,<br>Наукоград&nbsp;Фрязино, улица&nbsp;Вокзальная, 19,&nbsp;82"
      CEO: "Кирилл Аристов"

    dateLastEdited: "2 January 2006 в 15:04"
    datePosted: "2 January 2006, 15:04"

    CONTENTS: "Содержание"
    READ_MORE: "Читать далее…"
    FEED: "Трансляция"
    NEWER: "Раньше"
    OLDER: "Позже"
    PREVIOUS: "Предыдущая"
    NEXT: "Следующая"
    ON_FIRST: "На первой странице"
    ON_LAST: "На последней странице"
    DATE: "Дата"
    LOCATION: "Место"
    COORDINATES: "Координаты"
    TAGS: "Метки"

    HOME_PAGE: "Главная страница"
    LANG_TO: "Change Language to English"
    LANG_FROM: "&nbsp;На&nbsp;русском"

    LAST_EDITED: "Эта страница последний раз была отредактирована"
    PUBLISHED: "Эта страница была создана"
    EDIT_THIS_PAGE: "Редактировать страницу"
    EDIT_THIS_PAGE_TITLE: "Эту страницу можно изменять. О том, как вносить изменения — на странице «Как внести вклад»"

    PAGE: "Страница"
    SCROLL_UP: "Наверх"